server:
  port: 8761
eureka:
  instance:
    preferIpAddress : true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:root@localhost:8761/eureka/
spring:
  security:
    user:
      name: admin
      password: root