#server.port=8091
#spring.application.name=configServer
#eureka.client.service-url.defaultZone=http://admin:root@localhost:8761/eureka/
#spring.cloud.config.server.git.uri=https://github.com/smartiworld/config-properties
#spring.cloud.config.server.git.search-paths=/**
#spring.cloud.config.label=master
#spring.cloud.config.username=smartiworld
#spring.cloud.config.password=git@siworld163!
server:
  port: 8091
spring:
  application:
    name: configServer
  profiles: native,git
  cloud:
    config:
      server:
        native:
          search-locations: file:F:\github_work\config-properties
        git:
          uri: 