server:
  port: 8990
spring:
  application:
    name: micservice.user
eureka:
  instance:
    preferIpAddress : true
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:root@localhost:8761/eureka/
  