server:
  port: 8890
spring:
  application:
    name: micservice.ipay
eureka:
  instance:
    preferIpAddress : true
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:root@localhost:8761/eureka/

#MICSERVICE.USER:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    NFLoadBalancerPingClassName:
#    NIWSServerListClassName:
#    NIWSServerListFilterClassName: