server:
  port: 8190
eureka:
  instance:
    preferIpAddress : true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:root@localhost:8761/eureka/
zuul:
  ignored-services: '*'